[project]
name = "politipo"
version = "0.1.4"
description = "A library for seamless type conversions between Python data structures and models."
authors = [{ name = "Kevin Saltarelli", email = "kevinqz@gmail.com" }]
requires-python = ">=3.11"
dependencies = []